# Generated by Django 5.0.6 on 2024-07-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
